### ISSUE TITLE
Pure Bootique bootstrap of Cayenne projects

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#15]
Currently bootique-cayenne would support either pure Cayenne projects with DataNodes configured in cayenne-project.xml or single DataNode projects configured via Bootique. So a fairly common multi-DataNode projects that would previously use JNDI DataSource can not be configured in Bootique. 

One idea is to allow (optionally) to completely ignore ```cayenne-project.xml``` in Bootique and connect DataMaps to DataSources straight in the YAML. E.g.:

```yml
cayenne
  # default DataSource
  datasource: myds

  # current config - implicit classpath URLs
  configs:
    - cayenne-project.xml

  # maps config ... supports DataMap XML references in ResourceFactory format
  maps:
    - map: http://example.org/mymap1.map.xml
      datasource: myds1
    - map: classpath:mymap2.map.xml
      datasource: myds2
      # uses default DataSource
    - map: mymap3.map.xml 
```
