### ISSUE TITLE
"maps" config must be a dictionary, not a list for extensibility 

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#68]
_(this is a breaking change and should go to 2.0)_

So I have multiple modules contributing a single Cayenne project each. The app importing them needs to map each one of them to a different DataSource. Currently the only way to do it is in the app config itself, as the "cayenne.map" key is a list, and can't be glued together from different modules:

```yml
cayenne:
  maps:
    - datasource: ds1
      location: "classpath:m1.map.xml"
    - datasource: ds2
      location: "classpath:m2.map.xml"
```

If if turn it into a map, then each module can contribute its own thing, making things more easily pluggable:

```yml
# module 1
cayenne:
  maps:
    m1: 
      datasource: ds1
      location: "classpath:m1.map.xml"

# module 2
cayenne:
  maps:
    m2: 
      datasource: ds2
      location: "classpath:m2.map.xml"
