### ISSUE TITLE
Different way to add project or data map config in yml

### ISSUE THREAD

**Issue by aarrsseni** [bootique/bootique-cayenne#70]
Here is example of adding cayenne-project and datamap in one config:
```
cayenne:
  createSchema: true
  datasource: defaultds
  configs:
    - cayenne-project1.xml
  maps:
    - location: classpath:dm1.map.xml
      name: map1
      datasource: ds1
```
To add map we need to set location as `classpath:dm1.map.xml`
To add project we need to set as `cayenne-project1.xml` without `classpath:`
But there are both in the same directory.
We should make common pattern of adding projects or datamap.
