### ISSUE TITLE
Conflict of cayenne-projects

### ISSUE THREAD

**Issue by aarrsseni** [bootique/bootique-cayenne#71]
If user add cayenne-project in yml config
```
cayenne:
  createSchema: true
  datasource: defaultds
  configs:
    - cayenne-project.xml
```
And also add another cayenne-project
```
CayenneModule.extend(binder).addProject("cayenne-project1.xml")
```
Cayenne project from yml config will be thrown away without any logs.
At least we should log this.
